### ISSUE TITLE
Waiting for Spotify Quota Extension

### ISSUE THREAD

**Issue by Cutaiar** [Cutaiar/obsidian-song-links#5]
Until Spotify approves my [quota extension request](https://developer.spotify.com/dashboard/f73730e86de14041b47fc683e619fd8b/extension-requests), only users that have explicitly been given access will be able successfully use the plugin.

**Comment by myhd** [comment]
Still waiting? I'd love to use the plugin, but it appears to be not working, even after authorization.

**Comment by Cutaiar** [comment]
@myhd I'm glad you're interested! Yes, I'm working on fulfilling Spotify's requirements to pass the Quota Extension (as it already got denied once). Email me the email you use for your Spotify account and I can give you access in the mean time.

**Comment by Cutaiar** [comment]
Update: the first quota extension was denied on account of:

- Begins with Spot or used name similar in sound or spelling to "Spotify"
- Metadata, cover art and audio content must be accompanied by a Spotify logo and a link back to the applicable artist, album, track, or playlist on the Spotify Service

I've added an attribution to the inserted links and changed the name of the plugin to omit "Spotify" in version `0.3.0`. Waiting on a new quota extension submitted today.

**Comment by Cutaiar** [comment]
Update: the quote extension was approved and Song Links is publicly available. Update to `0.3.2` for the newest stuff!
